services:
  db:
    image: postgres:16-alpine
    container_name: uni-postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE} 
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./backend
    container_name: uni-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${PGDATABASE}
      SPRING_DATASOURCE_USERNAME: ${PGUSER}
      SPRING_DATASOURCE_PASSWORD: ${PGPASSWORD}
      SPRING_JPA_OPEN_IN_VIEW: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      args:
        VITE_API_URI: http://localhost:8080
    ports: ["8081:80"]
    depends_on: [api]


